Repository vertesia/composableai, pull requests merged in 2025-08, with the labels that each got.

#460 feat: add endpoint to update app installation settings
  packages/client/src/AppsApi.ts
Labels: enhancement

#471 fix: disable 'enter' keyboard key when making a collection
  packages/ui/src/features/store/collections/CreateCollection.tsx
Labels: bug, enhancement

#492 fix: recalculate embeddings respects requested type
  packages/workflow/src/system/recalculateEmbeddingsWorkflow.ts
Labels: bug
